# Docs: https://docs.github.com/en/actions


name: CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]


env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAMESPACE: ${{ env.REPO_OWNER }}
  DOCKER_IMAGE_NAME: php-nginx
  DOCKER_IMAGE_REPO: ${{ env.DOCKER_IMAGE_NAMESPACE }}/${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}


jobs:

  docker:
    name: Build Docker images

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Harden CI
        uses: step-security/harden-runner@v2.2.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            actions-results-receiver-production.githubapp.com:443
            auth.docker.io:443
            dl-cdn.alpinelinux.org:443
            github.com:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: ./bin/build;

      - name: Save Docker images
        run: docker image save $(docker images --format "{{.Repository}}:{{.Tag}}" "${{ env.DOCKER_IMAGE_REPO }}") | gzip -9 > docker_images.tgz

      - name: Upload Docker image artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker
          path: docker_images.tgz

  test-docker:
    name: Test Docker images

    needs: [docker]

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:

      - name: Harden CI
        uses: step-security/harden-runner@v2.2.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download Docker image artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker

      - name: Load Docker images
        run: gzip --uncompress --stdout docker_images.tgz | docker image load

      - name: Test Docker images
        run: ./bin/test;

  push-dockerhub:
    name: Push images to Docker Hub

    needs: [test-docker]
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:

      - name: Harden CI
        uses: step-security/harden-runner@v2.2.1
        with:
          egress-policy: audit

      # Need source code to push README file contents to Docker Hub
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download Docker image artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker

      - name: Load Docker images
        run: gzip --uncompress --stdout docker_images.tgz | docker image load

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        run: |
          for image_name in $(docker images --format "{{.Repository}}:{{.Tag}}" "${{ env.DOCKER_IMAGE_REPO }}"); do
            echo "Pushing ${image_name}";
            docker push "${image_name}";
          done;
